int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int is_palindrome(char *s);
int wildcmp(char *s1, char *s2);
int square_root(int n, int i);
int last_digit(int n);
int is_prime(int i, int j);
int compare_chars(char *s, char *ss);
char* last_char(char *s);
